### ISSUE TITLE
跪求网易云音乐 node.js api本地运行方法

### ISSUE THREAD

**Issue by love123724** [hqchqc/CloudMusic#1]
我本地localhost:3000成功了,就是访问不到接口，报404

**Comment by hqchqc** [comment]
能详细说说吗 比如报的什么错 我的是部署在服务器上的 可以帮你看一下

**Comment by hqchqc** [comment]
> 我本地本地主机：3000成功了，就是访问不到接口，报404

能详细说说吗比如报的什么错我的是部署在服务器上的可以帮你看一下

**Comment by love123724** [comment]
哈哈哈哈😄，我弄好了，谢谢

**Comment by love123724** [comment]
我出错是因为克隆项目时克隆的的是tag里的
